### ISSUE TITLE
BLT compatibility

### ISSUE THREAD

**Issue by danshumaker** [typhonius/acquia_cli#59]
**Feature request related to Acquia BLT usage**
I would imagine many users of acquia_cli would also use acquia/blt. But it appears they are incompatible in terms of composer packages.  

**Hoped for solution**
This feature request is to make them compatible via composer.

**Describe alternatives you've considered**
Currently we have to install acquia_cli in a different location ( or repo ) so as not to interfere with the current projects composer setup that frequently requires blt.  We can continue down this route but that is in-convenient when testing in a CI environment.  We could also try using the phar install methods to get around the issue.

**Additional context**
Current environments tested in are docksal and Gitlab and Acquia Cloud.

**Steps to reproduce**
```
mkdir new-repo-test
cd new-repo-test
composer install acquia/blt
composer install typhonius/acquia_cli
```
I also tried this in the reverse order:
```
cd new-repo-test
rm -rf *
composer install typhonius/acquia_cli
composer install acquia/blt
```
Neither of these work at the moment.

Attaching screenshot of error.  (Annotated-command & consolidation/robo issue)
![blt-acquia-cli-no-bueno](https://user-images.githubusercontent.com/358833/77768994-a43a5100-7019-11ea-8193-cc8e3e718e17.png)

**Comment by typhonius** [comment]
The reason for this is that Acquia Cli uses the newer release of Robo (2.x) whereas BLT <= 11 uses an older version (1.x).

It might be possible to support both Robo 1.x and Robo 2.x in order to support an installation into a BLT repo, but I would need to investigate that further over the coming weeks. 

For now, my recommendation would be to use the Phar method (as it can be installed globally and will self-update for you).

**Comment by typhonius** [comment]
I'm going to close this issue for now and will deal with a follow-up when I get a response from the BLT team.
