### ISSUE TITLE
The API token is expired during the code:switch task

### ISSUE THREAD

**Issue by aroq** [typhonius/acquia_cli#68]
**Describe the bug**
The API token is expired during the `code:switch` task if the backup procedure takes more than 5 minutes.

**To Reproduce**
Steps to reproduce the behavior including calling code:
1. Perform `code:switch` task on the environment with big DBs
2. See error:
  ```Are you sure you want to switch code on the preprod environment to branch: stable-***? (y/n) y
➜  Backing up DB (***) on Preprod
 Notification in-progress
4 mins [⚬⚬⚬⚬⚬⚬⚬⚬⚬➤⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬]   0% [error]  The access token has expired.
  ```

**Expected behavior**
Database backup is not performed until it was requested in an explicit way (with the separate option).

**Comment by aroq** [comment]
I think that the application has a general issue with expiring tokens when trying to retrieve the task status notification with the jobs which take more than 5 minutes (Acquia API token expire value) to complete, but I didn't check the code to be completely sure.

**Comment by typhonius** [comment]
Hi there, this was first reported in https://github.com/typhonius/acquia_cli/pull/36, however it was an enhancement that could be made to the underlying PHP SDK which was done here https://github.com/typhonius/acquia-php-sdk-v2/pull/49 with the commit https://github.com/typhonius/acquia-php-sdk-v2/commit/e643cecd5c94d33b804a9b2a0dca769ab7142f34

If you update your Acquia Cli to a more recent version, and re-install dependencies, then this will be resolved for you.

Otherwise, download the latest version of the .phar with the instructions in the readme to make updates easier. Hope this helps!

**Comment by aroq** [comment]
As for me, an issue described is still there: DB backup was not requested but still performed according to the code: https://github.com/typhonius/acquia_cli/blob/master/src/Commands/CodeCommand.php#L131

Backup should not be performed when not requested explicitly (For example for the PREPROD environment with huge DBs).

**Comment by aroq** [comment]
FYI: I have the expiring token issue with the following version of Acquia CLI:

```
AcquiaCli 2.0.4
```

**Comment by aroq** [comment]
Created a FR: https://github.com/typhonius/acquia_cli/issues/69

**Comment by typhonius** [comment]
Let me create a large database that I can test with, and I'll get back to this issue with a re-open if there are token issues.

**Comment by typhonius** [comment]
I added a large DB and then changed the `taskwait` time to be 15 minutes. Each db I backed up took 16 minutes but completed successfully so I'll keep this closed. If you have any additional commentary that would help further track down a token expiry issue please do put it into this issue.

**Comment by aroq** [comment]
I confirm that it started to work properly with the latest 'phar' version after `acquiacli self:update` execution. Thank you!
