### ISSUE TITLE
PHP Warning:  sem_remove()

### ISSUE THREAD

**Issue by felkeM** [typhonius/acquia_cli#79]
> PHP Warning:  sem_remove(): SysV semaphore 140702091352320 does not (any longer) exist in phar:///usr/local/bin/acquiacli/vendor/symfony/lock/Store/SemaphoreStore.php on line 94

PHP: 7.4.5

**Comment by typhonius** [comment]
Hi there, thanks for raising this. What was the command that you used when you got this error? Does this always happen or was this a one off?

**Comment by felkeM** [comment]
It does it for all of the commands except for "acquiacli self:update".

**Comment by typhonius** [comment]
Do you by any chance not have the php sysvsem extension installed? We use the Symfony lock trait in a pretty vanilla form here so it might be something in that library that's causing issues. Which OS is this on too?

**Comment by felkeM** [comment]
I am using Windows 10 with WSL - Ubuntu 18.04

**Comment by typhonius** [comment]
Hmm, I don't have a testing machine for Windows. It looks like you might have hit a WSL bug similar to the one here: https://github.com/microsoft/WSL/issues/4809

That in turn links to this one here https://github.com/microsoft/WSL/issues/3743 which seems to have been fixed in WSL2. 

If you're unable to use WSL2 then please use the `--no-lock` option in commands to skip semaphore locking.

**Comment by typhonius** [comment]
Marking this as closed now as I believe the issue to be sold. Please re-open if the above solutions don't resolve it.
